[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mentorhub-topic-api"
version = "0.1.0"
dependencies = [
	"flask",
	"joserfc",
	"pymongo",
	"pyinstaller"
]

[project.scripts]
api = "app.scripts.api:cli"
