openapi: 3.0.3
info:
  title: Topic API
  version: 3.0.1
paths:
  /api/topic:
    get:
      description: List all topics by Name and ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopicIdentifiers'
    post:
      description: Create a new Topic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Topic'
      responses:
        '201':
          $ref: '#/components/responses/Topic'
  /api/topic/{topicid}:
    get:
      description: Return a Topic by ID
      parameters:
        - $ref: '#/components/parameters/TopicId'
      responses:
        '200':
          $ref: '#/components/responses/Topic'
    patch:
      description: Update a Topic by ID
      parameters:
        - $ref: '#/components/parameters/TopicId'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/TopicIdentifiers'
                - $ref: '#/components/schemas/TopicProperties'
      responses:
        '200':
          $ref: '#/components/responses/Topic'
  /api/topic/{topicid}/resource:
    post:
      description: Add a resource to a topic
      parameters:
        - $ref: '#/components/parameters/TopicId'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Resource'
      responses:
        '200':
          $ref: '#/components/responses/Topic'
  /api/topic/{topicid}/resource/{resourceid}:
    patch:
      description: Update a resource on a topic
      parameters:
        - $ref: '#/components/parameters/TopicId'
        - $ref: '#/components/parameters/ResourceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
    delete:
      description: Remove a resource from a Topic
      parameters:
        - $ref: '#/components/parameters/TopicId'
        - $ref: '#/components/parameters/ResourceId'
      responses:
        '200':
          description: OK
  /api/health:
    get:
      responses:
        '200':
          description: OK
  /api/config:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
components:
  responses:
    Topic:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Topic'
  parameters:
    TopicId:
      name: topicid
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/TopicIdentifiers/properties/_id'
    ResourceId:
      name: resourceid
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Resource/properties/_id'
    PathId:
      name: pathid
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/PathIdentifiers/properties/_id'
  schemas:
    TopicIdentifiers:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
        name:
          type: string
          pattern: ^[ -~]+$
          maxLength: 256
    TopicProperties:
      type: object
      description: Conforms to Topics Schema version 3.0.1.2
      properties:
        status:
          type: string
          enum:
            - Active
            - Archived
        description:
          type: string
          pattern: ^[ -~]+$
          maxLength: 256
        category:
          type: string
          enum:
            - Foundations of ITSM
            - Design and Development
            - Infrastructure and Operations
            - Networking and Security
            - Development Tools and Practices
            - Data Management
            - Continuous Integration and Deployment
            - Monitoring and Performance
        skills:
          type: array
          items:
            $ref: '#/components/schemas/Skill'
        lastSaved:
          type: object
          description: Tracking breadcrumb
          properties:
            fromIp:
              description: Http Request remote IP address
              type: string
            byUser:
              description: UUID Of User
              type: string
            atTime:
              description: The date-time when last updated
              type: string
            correlationId:
              description: The logging correlation ID of the update transaction
              type: string
          additionalProperties: false
    TopicResources:
      properties:
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Resource'
    Topic:
      required:
        - name
      allOf:
        - $ref: '#/components/schemas/TopicIdentifiers'
        - $ref: '#/components/schemas/TopicProperties'
        - $ref: '#/components/schemas/TopicResources'
    Resource:
      type: object
      description: Conforms to Resources Schema version 1.0.2
      properties:
        name:
          type: string
          pattern: ^[ -~]+$
          maxLength: 256
        description:
          type: string
          pattern: ^[ -~]+$
          maxLength: 256
        link:
          type: string
          pattern: ^https:\/\/([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z-]{2,24}(:[0-9]{1,5})?(\/(([\w\-\.~]|%[a-fA-F0-9]{2}|[!\$&'\(\)\*\+,;=:@])*\/?)*)?
        skills:
          type: array
          items:
            type: number
        tags:
          type: array
          items:
            type: string
            enum:
              - $
              - Article
              - Book
              - Exam
              - Interactive
              - Lecture
              - Lesson
              - Reference
              - Tutorial
              - User Guide
              - Video
              - UI/UX
              - API
              - Data
              - SRE
    Skill:
      type: object
      description: The list of skills related to this topic
      properties:
        name:
          type: string
          pattern: ^[ -~]+$
          maxLength: 256
        status:
          type: string
          enum:
            - Active
            - Archived
        description:
          type: string
          pattern: ^[ -~]+$
          maxLength: 256
        mastery:
          type: string
          enum:
            - Candidate
            - Apprentice
            - Resident
            - Master
            - Distinguished
        speciality:
          type: string
          enum:
            - Generalist
            - UI/UX Engineer
            - API Engineer
            - Data Engineer
            - SRE Engineer
    Path:
      required:
        - name
      allOf:
        - $ref: '#/components/schemas/PathIdentifiers'
        - $ref: '#/components/schemas/PathProperties'
    PathIdentifiers:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 64
    PathProperties:
      type: object
      description: Conforms to Path Schema 1.0.0
      properties:
        status:
          type: string
          enum:
            - Active
            - Archived
        segments:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                maxLength: 64
              topics:
                type: array
                items:
                  type: string
    Config:
      type: object
      properties:
        apiVersion:
          type: string
          description: Semantic Version Number
        Stores:
          type: array
          items:
            type: object
            properties:
              CollectionName:
                description: Mongodb Collection name
                type: string
              Version:
                description: Schema Version for the collection
                type: string
              Filter:
                description: special Filter applied to collection
                type: string
        ConfigItems:
          type: array
          items:
            type: object
            properties:
              name:
                description: Conf Item Name (Env Var Name, File Name)
                type: string
              value:
                description: The value for that config item
                type: string
              from:
                description: Where the value was found
                type: string
                enum:
                  - default
                  - environment
                  - file
        enums:
          type: object
